version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: mymigrationtooldb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=mymigrationtooldb
    ports:
      - "5432:5432"